// localStorage key 보존
export const STORAGE_KEYS = {
  boardDraft: 'tenvi.board.draft',
  boardDrafts: 'tenvi.board.drafts',
  boardCategories: 'tenvi.board.categories',
  boardPosts: 'tenvi.board.posts',
  boardStorageMode: 'tenvi.board.storageMode',
  mapStorageMode: 'tenvi.map.storageMode',
  notesStorageMode: 'tenvi.notes.storageMode',
  profileSettingsStorageMode: 'tenvi.profileSettings.storageMode',
  tasksStorageMode: 'tenvi.tasks.storageMode',
  userProfile: 'tenvi.user.profile',
  calendarEvents: 'tenvi.calendar.events',
  hudEffect: 'tenvi.hudEffect',
  language: 'tenvi.language',
  notes: 'tenvi.notes',
  startModule: 'tenvi.startModule',
  tasks: 'todo-manager-lite.todos',
  theme: 'tenvi.theme',
  timerCompletedSessions: 'tenvi.timer.completedSessions',
}
